// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Strip Docker --env-file quotes if present (dotenv already strips for local CLI).
    url: (() => {
      const raw =
        process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"] ?? "";
      const trimmed = raw.trim();
      if (
        (trimmed.startsWith('"') && trimmed.endsWith('"')) ||
        (trimmed.startsWith("'") && trimmed.endsWith("'"))
      ) {
        return trimmed.slice(1, -1);
      }
      return trimmed || undefined;
    })(),
  },
});
